[package]
name = "implicit-newton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sparse21 = "0.2.1"
itertools = "0.10.5"
textplots = "0.8.0"
rayon = "1.6.1"
