#!/bin/sh

cargo install --path .
cargo install --path ./impl_analysis
cargo install --path ./impl_benchmark
for n in impl_plt.py impl_pre_hydro.py impl_post_hydro.py riemann.py gubser.py plt_setting.py impl_observables.py; do
	cp utils/$n $HOME/.cargo/bin
done
